### PR TITLE
This is the 2nd Version of the Marky Basketball Cards

### PR DESCRIPTION
**Pull request by mlester0806**
Hello author, you should consider this modifications that I made with your wonderful website. Thank you!

### CODE REVIEW

**Review by mlester999 — CHANGES_REQUESTED** [review]
Hello bro, you should check the words that you used. It has some wrong grammar. Thank you.

**Review by mlester0806 — COMMENTED** [review]
Hello author, I've already change your request. Please check it out!

**Review by mlester999 — APPROVED** [review]
Wow this is really great bro! I will approve this right now. Thank you for making a fork with my website. Stay safe!

**Comment by mlester999** [comment]
I really loved it!

**Pull request merged**
